config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:index]
  resources :tasks, except: [:destroy]

   root 'users#index'

   get '/users/sign_in' => 'users#sign_in', :as => 'sign_in'
   post '/users/create' => 'users#user_create', :as => 'create_user'

   post '/tasks/index' => 'tasks#index', :as => 'log_in'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	require 'rest_client'

	def index
		 begin
     	  a = RestClient.get "http://recruiting-api.nextcapital.com/users/"+session[:user_id].to_s+"/todos.json?api_token="+session[:api_token], :Content_type => 'application/json'
     	  rescue => e	
     		 response_code = e.response.code
	          	if response_code == 400
	              	flash[:notice] = "Something went wrong. Please try again"
	              	redirect_to root_path and return
	            end  	
	  	 end
    	@todos = JSON.parse(a)
  	end

	def edit
		@id = params["id"]
	end

	def update
		 task_id = params["id"]
		 
		 if params["is_complete"].to_i == 1
		 	todo = {"todo" => {"description" => "Updated description", "is_complete" => true}}
		 	api_token = {"api_token" => session[:api_token] }
		 	data = api_token.merge(todo)
		 	put = RestClient.put "http://recruiting-api.nextcapital.com/users/"+session[:user_id].to_s+"/todos/"+task_id, data, :Content_type => 'application/json'
		 	redirect_to tasks_path
		 else
		 	redirect_to tasks_path
		 end
	end

	def new
		
	end

	def create
		todo = params.to_hash
		api_token = {"api_token" => session[:api_token] }
		payload = todo.merge(api_token)
		payload["api_token"]
		api_token = {"api_token" => session[:api_token] }
		request = {"api_token" => payload["api_token"], "todo" => {"description" => payload["description"]}}.to_json
		post = RestClient.post "http://recruiting-api.nextcapital.com/users/"+session[:user_id].to_s+"/todos", request, :Content_type => 'application/json'
		redirect_to tasks_path
	end

	def log_in
		 begin
     		payload = params.to_json
       		post = RestClient.post 'http://recruiting-api.nextcapital.com/users/sign_in', payload, :Content_type => 'application/json'
     	 rescue => e
       		 response_code = e.response.code
	         	if response_code == 400
	             	 flash[:notice] = "Invalid email/password. Please try again."
	            	 redirect_to root_path and return
	            end
         end  
         redirect_to log_in_path        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 require 'rest_client'

 	
  def index
  end
 

 def sign_in
     begin
     	payload = params.to_json
      post = RestClient.post 'http://recruiting-api.nextcapital.com/users/sign_in', payload, :Content_type => 'application/json'
     rescue => e
      p "******sign_in*************"
        p response_code = e.response.code
        #p response_code = e.response.body
          if response_code == 400
              flash[:notice] = "Invalid email/password. Please try again."
              redirect_to root_path and return
          end    
      end     
      redirect_to tasks_path      
  end

  def user_create
    begin
  	  payload = params.to_json
      post = RestClient.post 'http://recruiting-api.nextcapital.com/users', payload, :Content_type => 'application/json'
    rescue => e
      response_code = e.response.code
        if response_code == 400
           flash[:notice] = "Please choose another email."
           redirect_to root_path and return
        end
    end
      todo = JSON.parse(post.body)
      session[:user_id] =  todo["id"]
      session[:api_token] = todo["api_token"]
      session[:todos] =  todo["todos"]
      redirect_to log_in_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiConsumer</title>

   <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
   <script src="//code.jquery.com/jquery-1.10.2.js"></script>
   <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <%= javascript_include_tag "vendor/modernizr" %>

    <% flash.each do |key, value| %>
  		<%= content_tag :div, value, class: "flash #{key}" %>
	<% end %>

</head>
<body>
	<script>$("#sortable").sortable();</script>
  
<%= yield %>

</body>
</html>

app/views/tasks/edit.html.erb
<h2>This is the edit page for task id: <%= @id %></h2>
	
<div class="small-3 columns">
  <%= form_tag task_path, :method => :put %>
   Complete?: <%=check_box_tag :is_complete%><br/>
   <button class="button">Update</button>
</div>
  
   

app/views/tasks/index.html.erb
<div class="task_table">
  <%if @todos.present? %>
    <p>Below is the list of tasks</p>
    <table> 
      <thead>
        <tr>
          <th>ID</th>
          <th>Description</th>
          <th>Complete?</th>
          <th>Edit</th>
        </tr>
      </thead>
        <tbody>
        <%@todos.each do |h|%>
        <tr>
           <td><%=h["id"]%></td>
           <td><%=h["description"]%></td>
           <td><%=h["is_complete"]%></td>
           <td>
           <%= link_to "Edit", edit_task_path(h["id"])%>
           </td>
         </tr>
        <%end%>
       </tbody>
     </table>
    <%else%>
      <p>No Tasks are Found</p>
  <%end%>
</div>

  <div class="create_new">
    <%= link_to "Create New Task", new_task_path %>
  </div>

app/views/tasks/new.html.erb
<div class="small-3 columns">
	<%= form_tag tasks_path %>
   Description: <%=text_field_tag :description%><br/>
  
   <button class="button">Save</button>
</div>   

app/views/tasks/show.html.erb
<%= link_to "Create New Task", new_task_path %>
<%if @todos.present? %>
  <p>Below is the list of tasks</p>
  <table> 
    <thead>
      <tr>
        <th>ID</th>
        <th>description</th>
        <th>is complete</th>
      </tr>
    <thead>
    <tbody>
    <%@todos.each do |h|%>
    <tr>
      <td><%=h["id"]%></td>
      <td><%=h["description"]%></td>
      <td><%=h["is_complete"]%></td>
      <td>
      <%= link_to "Edit", edit_task_path(h["id"])%>
      </td>
    </tr>
   <%end%>
 </tbody>
  </table>
<%else%>
  <p>No Tasks are Found</p>
<%end%>

app/views/users/index.html.erb
<div class="sign-in">
 <div class="small-3 columns">
	<%= form_tag create_user_path, :method => :post do %>
	   Email: <%=text_field_tag :email%><br />
	   Password:<%=password_field_tag :password%><br />
	   
	    <button class="button">Sign up</button>

	<%end%>

 </div>
</div>  	

<%= flash[:message] %>

app/views/users/new.html.erb
<%= form_tag users_path, :method => :post do %>
   email : <%=text_field_tag :email%><br />
   first_name :<%=text_field_tag :first_name%><br />
   last_name :<%=text_field_tag :last_name%><br/><br/>
   <%=submit_tag "save"%>
<%end%>

app/views/users/show.html.erb
<%= form_tag log_in_path, :method => :post do %>
   email : <%=text_field_tag :email%><br />
   password :<%=text_field_tag :password%><br />
   
   <%=submit_tag "login"%>
<%end%>

app/views/users/sign_in.html.erb
<%= form_tag sign_in_path, :method => :post do %>
   email : <%=text_field_tag :email%><br />
   password :<%=text_field_tag :password%><br />
   
   <%=submit_tag "login"%>
<%end%>

app/views/users/user_create.html.erb
<%= form_tag log_in_path, :method => :post do %>
   email : <%=text_field_tag :email%><br />
   password :<%=text_field_tag :password%><br />
   
   <%=submit_tag "login"%>
<%end%>